### ISSUE TITLE
Kindly asking for a new name?

### ISSUE THREAD

**Issue by sylvinus** [richardgorman/AtomCSS#1]
Hi Richard!

I'm the organizer of http://dotcss.io (which happens tomorrow :). As it's early in your project, I just wanted to ask if you could consider choosing another name for the project, as it might confuse people & google?

Thanks!

**Comment by richardgorman** [comment]
Hi, my apologies for that. I have renamed the repository =)

I hope the event goes well!

**Comment by sylvinus** [comment]
No need to apologize! Thank you so much. If you want to attend next year I'll be happy to give you a free ticket ;)

**Comment by richardgorman** [comment]
I'll take you up on that offer. That would be awesome!

**Comment by sylvinus** [comment]
:-) Just shoot me an email next year when we announce the date then :)
